<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MFF Craft</title>
    <link rel="stylesheet" href="https://jc.ggu.cz/pico.css">
</head>
<body>
<main class="container">
    <article>
        <header>
            <h1>MFF Craft</h1>
        </header>
        <section>
            <h2>Add player</h2>
            <form action="/save-player/" method="post">
                <label for="nickname"></label><input type="text" id="nickname" name="nickname">
                <button id="submit">Submit</button>
            </form>
        </section>
        <footer>
            <p>Repository: <a href="https://github.com/yagarea/minecraft-matfyz">Github.com/yagarea/minecraft-matfyz</a></p>
        </footer>
    </article>
</main>
</body>