<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MFF Craft</title>
    <link rel="stylesheet" href="https://jc.ggu.cz/pico.css">
</head>
<body>
<main class="container">
    <article>
        <header>
            <h1>MFF Craft</h1>
        </header>
        <section>
            <div>
                <a role="button" class="contrast outline" href="${cz.blackblog.website.WebServer.getCasAuthURL()}">Login with CAS (WIP)</a>
                <a role="button" href="/login/">Native login</a>
            </div>
        </section>
        <footer>
            <p>Repository: <a href="https://github.com/yagarea/minecraft-matfyz">Github.com/yagarea/minecraft-matfyz</a></p>
        </footer>
    </article>
</main>
</body>